USE aviation_dw;

CREATE EXTERNAL TABLE IF NOT EXISTS flight_fact (
    flight_id BIGINT,

    fl_date STRING,

    airline_code STRING,

    fl_number STRING,

    origin_airport_code STRING,
    dest_airport_code STRING,

    crs_dep_time STRING,
    dep_time DOUBLE,

    crs_arr_time STRING,
    arr_time DOUBLE,

    dep_delay DOUBLE,
    arr_delay DOUBLE,

    distance DOUBLE,

    cancelled DOUBLE,
    diverted DOUBLE
)
STORED AS PARQUET
LOCATION '/user/hive/warehouse/aviation/flight_fact';
